import request from 'supertest'
import { afterEach, beforeEach, describe, expect, it } from 'vitest'
import { makeCtx, anonDoc, HQ, type TestCtx } from './helpers.js'

describe('collaboration', () => {
  let ctx: TestCtx
  beforeEach(() => {
    ctx = makeCtx()
  })
  afterEach(() => {
    ctx.db.close()
  })

  it('appends chat messages to the chat fence with a server-stamped kind', async () => {
    const { id, key } = await anonDoc(ctx.app, HQ)
    const res = await request(ctx.app)
      .post(`/api/docs/${id}/chat/message`)
      .set('x-share-key', key)
      .send({ text: 'on it', author: 'builder-1' })
    expect(res.status).toBe(200)
    const content = await request(ctx.app).get(`/api/docs/${id}/content`).set('x-share-key', key)
    expect(content.text).toContain('@builder-1 (guest): on it')
    const events = await request(ctx.app).get(`/api/docs/${id}/events`).set('x-share-key', key)
    const chatEvent = events.body.events.find((e: { type: string }) => e.type === 'chat.message')
    expect(chatEvent.payload.kind).toBe('guest')
    expect(chatEvent.payload.text).toBe('on it')
  })

  it('updates status fences and logs awaiting-human notifications', async () => {
    const { id, key } = await anonDoc(ctx.app, HQ)
    const res = await request(ctx.app)
      .post(`/api/docs/${id}/status`)
      .set('x-share-key', key)
      .send({ state: 'awaiting-human', note: 'Need a decision', headline: 'Decision needed' })
    expect(res.status).toBe(200)
    expect(res.body.state).toBe('awaiting-human')
    const content = await request(ctx.app).get(`/api/docs/${id}/content`).set('x-share-key', key)
    expect(content.text).toContain('state: awaiting-human')
    expect(content.text).toContain('Need a decision')
    const logs = ctx.db.prepare('SELECT * FROM notify_log WHERE doc_id=?').all(id)
    expect(logs.length).toBe(1)
    const missing = await request(ctx.app)
      .post(`/api/docs/${id}/status`)
      .set('x-share-key', key)
      .send({ state: 'awaiting-human' })
    expect(missing.status).toBe(400)
  })

  it('records ephemeral typing on the events response', async () => {
    const { id, key } = await anonDoc(ctx.app, HQ)
    await request(ctx.app).post(`/api/docs/${id}/typing`).set('x-share-key', key).send({})
    const events = await request(ctx.app)
      .get(`/api/docs/${id}/events?since=latest`)
      .set('x-share-key', key)
    expect(events.body.typing).toContain('Guest')
  })

  it('supports anchored comments, replies, and resolution', async () => {
    const { id, key } = await anonDoc(ctx.app, HQ)
    const anchored = await request(ctx.app)
      .post(`/api/docs/${id}/comments`)
      .set('x-share-key', key)
      .send({ body: 'this wording is off', find: 'Ship the API' })
    expect(anchored.status).toBe(201)
    expect(anchored.body.anchored).toBe(true)
    const cid = anchored.body.id as string
    const reply = await request(ctx.app)
      .post(`/api/docs/${id}/comments/${cid}/replies`)
      .set('x-share-key', key)
      .send({ body: 'agreed' })
    expect(reply.status).toBe(201)
    const resolved = await request(ctx.app)
      .post(`/api/docs/${id}/comments/${cid}/resolve`)
      .set('x-share-key', key)
      .send({ resolved: true })
    expect(resolved.status).toBe(200)
    const list = await request(ctx.app).get(`/api/docs/${id}/comments`).set('x-share-key', key)
    expect(list.body.comments[0].resolved).toBe(true)
    expect(list.body.comments[0].replies.length).toBe(1)
  })

  it('applies replace suggestions as a delete+insert pair', async () => {
    const { id, key } = await anonDoc(ctx.app, HQ)
    const created = await request(ctx.app)
      .post(`/api/docs/${id}/suggestions`)
      .set('x-share-key', key)
      .send({ type: 'replace', find: 'Ship the API', text: 'Ship the API with retries' })
    expect(created.status).toBe(201)
    expect(created.body.ids.length).toBe(2)
    const pending = await request(ctx.app)
      .get(`/api/docs/${id}/suggestions`)
      .set('x-share-key', key)
    expect(pending.body.suggestions.every((s: { status: string }) => s.status === 'pending')).toBe(
      true,
    )
    const accept = await request(ctx.app)
      .post(`/api/docs/${id}/suggestions/${created.body.ids[0]}`)
      .set('x-share-key', key)
      .send({ action: 'accept' })
    expect(accept.status).toBe(200)
    const content = await request(ctx.app).get(`/api/docs/${id}/content`).set('x-share-key', key)
    expect(content.text).toContain('- [ ] Ship the API with retries @builder-1 #p1')
    expect(content.text.endsWith('\nShip the API with retries')).toBe(false)
  })

  it('keeps revisions, pages them, and restores', async () => {
    const { id, key } = await anonDoc(ctx.app, '# v1\n')
    const v1 = await request(ctx.app).get(`/api/docs/${id}/content`).set('x-share-key', key)
    await request(ctx.app)
      .put(`/api/docs/${id}/content`)
      .set('x-share-key', key)
      .set('if-match', v1.headers['x-doc-version'])
      .send({ content: '# v2\n', label: 'second' })
    const revs = await request(ctx.app).get(`/api/docs/${id}/revisions`).set('x-share-key', key)
    expect(revs.body.revisions.length).toBe(2)
    const restore = await request(ctx.app)
      .post(`/api/docs/${id}/restore`)
      .set('x-share-key', key)
      .send({ revision: revs.body.revisions[1].id })
    expect(restore.status).toBe(200)
    const content = await request(ctx.app).get(`/api/docs/${id}/content`).set('x-share-key', key)
    expect(content.text).toContain('# v1')
  })

  it('long-polls events with mention filtering and pages at 200', async () => {
    const { id, key } = await anonDoc(ctx.app, HQ)
    await request(ctx.app)
      .post(`/api/docs/${id}/chat/message`)
      .set('x-share-key', key)
      .send({ text: '@scout check this', author: 'builder-1' })
    const mentioned = await request(ctx.app)
      .get(`/api/docs/${id}/events?since=0&wait=1&mention=scout`)
      .set('x-share-key', key)
    expect(mentioned.body.events.length).toBeGreaterThan(0)
    expect(mentioned.body.events[0].payload.text).toContain('@scout')
    const other = await request(ctx.app)
      .get(`/api/docs/${id}/events?since=0&wait=1&mention=nobody`)
      .set('x-share-key', key)
    expect(other.body.events.length).toBe(0)
    for (let i = 0; i < 205; i++) {
      ctx.services.emit(id, 'content.replaced', `a${i}`, false, {})
    }
    const capped = await request(ctx.app).get(`/api/docs/${id}/events`).set('x-share-key', key)
    expect(capped.body.events.length).toBe(200)
    expect(capped.body.capped).toBe(true)
    expect(capped.body.tip).toBeTruthy()
  })

  it('rejects chat when no chat fence exists', async () => {
    const { id, key } = await anonDoc(ctx.app, '# plain\n')
    const res = await request(ctx.app)
      .post(`/api/docs/${id}/chat/message`)
      .set('x-share-key', key)
      .send({ text: 'hi' })
    expect(res.status).toBe(400)
  })
})
