import request from 'supertest'
import { afterEach, beforeEach, describe, expect, it } from 'vitest'
import { makeCtx, anonDoc, mintRole, account, type TestCtx } from './helpers.js'

describe('docs core', () => {
  let ctx: TestCtx
  beforeEach(() => {
    ctx = makeCtx()
  })
  afterEach(() => {
    ctx.db.close()
  })

  it('creates anonymous docs via POST /new and redirects via GET /new', async () => {
    const res = await request(ctx.app).post('/new').send({ title: 'Plan', content: '# Plan\n' })
    expect(res.status).toBe(201)
    expect(res.body.id).toMatch(/^[A-Za-z0-9_-]{22}$/)
    expect(res.body.key).toBeTruthy()
    expect(res.body.url).toContain(`/d/${res.body.id}?key=`)
    const redirect = await request(ctx.app).get('/new')
    expect(redirect.status).toBe(303)
    expect(redirect.headers.location).toMatch(/^\/d\/[A-Za-z0-9_-]+\?key=/)
  })

  it('reads content as markdown with version headers', async () => {
    const { id, key } = await anonDoc(ctx.app, '# Hello\n')
    const res = await request(ctx.app).get(`/api/docs/${id}/content`).set('x-share-key', key)
    expect(res.status).toBe(200)
    expect(res.headers['content-type']).toContain('text/markdown')
    expect(res.headers['x-doc-version']).toBeTruthy()
    expect(res.headers.etag).toContain('"')
    expect(res.text).toBe('# Hello\n')
  })

  it('rejects stale writes with 409 and accepts retry', async () => {
    const { id, key } = await anonDoc(ctx.app, '# v1\n')
    const read = await request(ctx.app).get(`/api/docs/${id}/content`).set('x-share-key', key)
    const version = read.headers['x-doc-version'] as string
    const stale = await request(ctx.app)
      .put(`/api/docs/${id}/content`)
      .set('x-share-key', key)
      .set('if-match', 'stale-version')
      .send({ content: '# v2\n' })
    expect(stale.status).toBe(409)
    expect(stale.body.currentVersion).toBe(version)
    expect(stale.body.use).toBeTruthy()
    const ok = await request(ctx.app)
      .put(`/api/docs/${id}/content`)
      .set('x-share-key', key)
      .set('if-match', version)
      .send({ content: '# v2\n' })
    expect(ok.status).toBe(200)
    expect(ok.body.ok).toBe(true)
    expect(ok.body.version).not.toBe(version)
  })

  it('enforces the blind-wipe guard', async () => {
    const big = `# Big\n\n${'x'.repeat(2500)}`
    const { id, key } = await anonDoc(ctx.app, big)
    const wiped = await request(ctx.app)
      .put(`/api/docs/${id}/content`)
      .set('x-share-key', key)
      .send({ content: '' })
    expect(wiped.status).toBe(409)
    expect(wiped.body.error).toContain('wipe')
    const forced = await request(ctx.app)
      .put(`/api/docs/${id}/content`)
      .set('x-share-key', key)
      .set('x-allow-clear', '1')
      .send({ content: 'small' })
    expect(forced.status).toBe(200)
  })

  it('requires content on PUT and 405s PATCH with Allow', async () => {
    const { id, key } = await anonDoc(ctx.app)
    const missing = await request(ctx.app)
      .put(`/api/docs/${id}/content`)
      .set('x-share-key', key)
      .send({})
    expect(missing.status).toBe(400)
    expect(missing.body.error).toBe('content required')
    const patch = await request(ctx.app)
      .patch(`/api/docs/${id}/content`)
      .set('x-share-key', key)
      .send({ content: 'x' })
    expect(patch.status).toBe(405)
    expect(patch.headers.allow).toContain('PUT')
  })

  it('enforces share roles: view cannot write, suggest cannot replace', async () => {
    const { id, key } = await anonDoc(ctx.app, '# Doc\n')
    const view = await mintRole(ctx.app, id, key, 'view')
    const blocked = await request(ctx.app)
      .put(`/api/docs/${id}/content`)
      .set('x-share-key', view)
      .send({ content: 'x' })
    expect(blocked.status).toBe(403)
    const suggest = await mintRole(ctx.app, id, key, 'suggest')
    const suggestWrite = await request(ctx.app)
      .put(`/api/docs/${id}/content`)
      .set('x-share-key', suggest)
      .send({ content: 'x' })
    expect(suggestWrite.status).toBe(403)
    const comment = await mintRole(ctx.app, id, key, 'comment')
    const commentWrite = await request(ctx.app)
      .post(`/api/docs/${id}/comments`)
      .set('x-share-key', comment)
      .send({ body: 'note' })
    expect(commentWrite.status).toBe(201)
  })

  it('share minting is idempotent per role and revocable', async () => {
    const { id, key } = await anonDoc(ctx.app)
    const first = await mintRole(ctx.app, id, key, 'view')
    const second = await mintRole(ctx.app, id, key, 'view')
    expect(first).toBe(second)
    const revoke = await request(ctx.app)
      .delete(`/api/docs/${id}/shares/${first}`)
      .set('x-share-key', key)
    expect(revoke.status).toBe(200)
    const after = await request(ctx.app).get(`/api/docs/${id}/content`).set('x-share-key', first)
    expect(after.status).toBe(401)
  })

  it('blocks guest impersonation of account usernames', async () => {
    await account(ctx.app, 'alice')
    const { id, key } = await anonDoc(ctx.app)
    const res = await request(ctx.app)
      .post(`/api/docs/${id}/comments`)
      .set('x-share-key', key)
      .send({ body: 'hi', author: 'alice' })
    expect(res.status).toBe(409)
    const ok = await request(ctx.app)
      .post(`/api/docs/${id}/comments`)
      .set('x-share-key', key)
      .send({ body: 'hi', author: 'alice-agent' })
    expect(ok.status).toBe(201)
    expect(ok.body.id).toBeTruthy()
  })

  it('claims anonymous docs into sessions and duplicates owned docs', async () => {
    const { agent } = await account(ctx.app, 'bob')
    const { id, key } = await anonDoc(ctx.app, '# Mine\n')
    const claimed = await agent.post(`/api/docs/${id}/claim`).set('x-share-key', key).send({})
    expect(claimed.status).toBe(200)
    const meta = await agent.get(`/api/docs/${id}`).set('x-share-key', key)
    expect(meta.body.role).toBe('owner')
    const dup = await agent.post(`/api/docs/${id}/duplicate`).send({})
    expect(dup.status).toBe(201)
    expect(dup.body.doc.id).not.toBe(id)
  })

  it('lists owned docs and reports unclaimed metadata', async () => {
    const { agent } = await account(ctx.app, 'carol')
    const owned = await agent.post('/api/docs').send({ title: 'Owned', content: '# O\n' })
    expect(owned.status).toBe(201)
    const list = await agent.get('/api/docs')
    expect(list.body.docs.some((d: { title: string }) => d.title === 'Owned')).toBe(true)
    const { id, key } = await anonDoc(ctx.app, `# Anonymous\n\n${'y'.repeat(600)}`)
    const meta = await request(ctx.app).get(`/api/docs/${id}`).set('x-share-key', key)
    expect(meta.body.unclaimed).toBe(true)
    const content = await request(ctx.app).get(`/api/docs/${id}/content`).set('x-share-key', key)
    expect(content.headers['x-workbench-unclaimed']).toBeTruthy()
  })

  it('accepts feedback and returns JSON 404 for unknown api routes', async () => {
    const { id, key } = await anonDoc(ctx.app)
    const fb = await request(ctx.app)
      .post(`/api/docs/${id}/feedback`)
      .set('x-share-key', key)
      .send({ summary: 'The 409 response was clear enough', category: 'api' })
    expect(fb.status).toBe(200)
    const nf = await request(ctx.app).get('/api/does-not-exist')
    expect(nf.status).toBe(404)
    expect(nf.body.error).toBe('route not found')
  })
})
